<script lang="ts">
  import Icon from '$lib/components/Icon.svelte';
  import { buyerProfile, saveBuyerProfile } from '$lib/stores/buyer';
  let form={...$buyerProfile};
  function save(){form.initials=form.name.split(/\s+/).slice(0,2).map((part)=>part[0]?.toUpperCase()).join('')||'AG';saveBuyerProfile({...form});}
</script>
<svelte:head><title>Account settings — AssetGuru</title></svelte:head>
<header class="page-head"><div><span class="eyebrow">Buyer account</span><h1>Account <span class="gradient-text">settings.</span></h1><p>Manage your profile and marketplace communication preferences.</p></div></header>
<form class="settings-grid" onsubmit={(event)=>{event.preventDefault();save();}}>
  <section class="profile glass"><div class="panel-head"><div><span class="eyebrow">Public identity</span><h2>Profile details</h2></div><i class={`avatar ${form.avatarTone}`}>{form.initials}</i></div><div class="two"><label>Full name<input bind:value={form.name} required/></label><label>Email address<input type="email" bind:value={form.email} required/></label></div><div class="two"><label>Studio / role<input bind:value={form.studio}/></label><label>Country<select bind:value={form.country}><option>United Kingdom</option><option>United States</option><option>European Union</option><option>Other</option></select></label></div><label>Avatar colour<div class="tones"><button type="button" class="cyan" class:active={form.avatarTone==='cyan'} onclick={()=>form.avatarTone='cyan'}>Cyan</button><button type="button" class="violet" class:active={form.avatarTone==='violet'} onclick={()=>form.avatarTone='violet'}>Violet</button><button type="button" class="magenta" class:active={form.avatarTone==='magenta'} onclick={()=>form.avatarTone='magenta'}>Magenta</button></div></label></section>
  <aside><section class="preferences glass"><span class="eyebrow">Notifications</span><h2>Communication</h2><label class="toggle"><span><b>Product update emails</b><small>Compatibility releases and important package changes.</small></span><input type="checkbox" bind:checked={form.updateEmails}/></label><label class="toggle"><span><b>Marketplace discoveries</b><small>Occasional collections, creator launches and promotions.</small></span><input type="checkbox" bind:checked={form.marketing}/></label></section><section class="security glass"><Icon name="shield" size={28}/><h3>Security foundation</h3><p>Production accounts will use verified email, secure sessions and optional multi-factor authentication through Supabase Auth.</p><button class="button button-secondary" type="button" disabled>Configure MFA in production</button></section></aside>
  <button class="button button-primary save" type="submit"><Icon name="check" size={18}/> Save account settings</button>
</form>
<style>
  .page-head{margin-bottom:20px}.page-head h1{margin:10px 0 7px;font-size:clamp(2.5rem,4vw,4.3rem);line-height:.96;letter-spacing:-.06em}.page-head p{margin:0;color:#aab5c8}.settings-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:14px;align-items:start}.profile,.preferences,.security{padding:21px;border-radius:16px}.panel-head{margin-bottom:18px;display:flex;justify-content:space-between;align-items:center}.panel-head h2,.preferences h2{margin:6px 0 0}.avatar{width:58px;height:58px;display:grid;place-items:center;border-radius:16px;color:#031018;font-style:normal;font-weight:950}.avatar.cyan{background:linear-gradient(135deg,#00e5ff,#24d89a)}.avatar.violet{background:linear-gradient(135deg,#8b5cf6,#00e5ff)}.avatar.magenta{background:linear-gradient(135deg,#ff3fd8,#8b5cf6)}.profile>label,.two label{margin-top:13px;display:grid;gap:7px;color:#aab5c8;font-size:9px}.two{display:grid;grid-template-columns:1fr 1fr;gap:11px}.profile input,.profile select{min-height:45px;padding:0 11px;border:1px solid #183352;border-radius:9px;outline:0;color:#f5f8ff;background:#050a16}.profile input:focus,.profile select:focus{border-color:#00e5ff}.tones{display:flex;gap:8px}.tones button{min-height:40px;padding:0 14px;border:1px solid #183352;border-radius:9px;color:#f5f8ff;cursor:pointer}.tones button.cyan{background:rgb(0 229 255/.1)}.tones button.violet{background:rgb(139 92 246/.12)}.tones button.magenta{background:rgb(255 63 216/.1)}.tones button.active{border-color:#00e5ff;box-shadow:0 0 16px rgb(0 229 255/.13)}.toggle{padding:15px 0;display:grid;grid-template-columns:1fr auto;gap:12px;border-top:1px solid #122a43}.toggle span{display:grid}.toggle b{font-size:10px}.toggle small{margin-top:4px;color:#718096;font-size:8px;line-height:1.45}.toggle input{width:38px;height:20px;accent-color:#00e5ff}.security{margin-top:14px;color:#8b5cf6}.security h3{color:#f5f8ff}.security p{color:#aab5c8;font-size:9px;line-height:1.6}.security .button{width:100%;font-size:9px;opacity:.55;cursor:not-allowed}.save{grid-column:1/-1;justify-self:end;min-width:240px}
  @media(max-width:850px){.settings-grid{grid-template-columns:1fr}.save{justify-self:stretch}}@media(max-width:600px){.two{grid-template-columns:1fr}.tones{display:grid}.save{width:100%}}
</style>
