<script lang="ts">
  import Icon from '$lib/components/Icon.svelte';
  import { getAsset } from '$lib/data/marketplace';
  import { availableUpdates, dismissUpdate, entitlements, recordDownload, type BuyerEntitlementWithAsset } from '$lib/stores/buyer';

  let current: BuyerEntitlementWithAsset[] = [];
  $: {
    const items: BuyerEntitlementWithAsset[] = [];
    for (const entry of $entitlements) {
      const asset = getAsset(entry.slug);
      if (asset && asset.version === entry.purchasedVersion) items.push({ ...entry, asset });
    }
    current = items;
  }
</script>
<svelte:head><title>Product updates — AssetGuru</title></svelte:head>
<header class="page-head"><div><span class="eyebrow">Compatibility watch</span><h1>Product <span class="gradient-text">updates.</span></h1><p>See exactly what changed before bringing a new asset version into your GameGuru MAX project.</p></div><a class="button button-secondary" href="/library"><Icon name="library" size={18}/> Open library</a></header>
<section class="hero glass"><div><Icon name="download" size={28}/></div><span><b>{$availableUpdates.length} {$availableUpdates.length===1?'update':'updates'} ready</b><small>Updates remain optional. Your purchased versions stay available in the library.</small></span><em>MAX compatibility monitored</em></section>
{#if $availableUpdates.length}<div class="updates">{#each $availableUpdates as update}<article class="update glass"><img src={update.asset.image} alt=""/><div class="copy"><div class="title"><span><small>{update.asset.category}</small><h2>{update.asset.title}</h2><a href={`/creators/${update.asset.creatorSlug}`}>{update.asset.creator} ✓</a></span><em>v{update.purchasedVersion} → v{update.latestVersion}</em></div><p>{update.asset.summary}</p><div class="changes"><span><Icon name="check" size={15}/> Improved GameGuru MAX {update.asset.maxVersion} compatibility</span><span><Icon name="check" size={15}/> Updated package documentation and examples</span><span><Icon name="check" size={15}/> Performance and naming consistency pass</span></div><div class="meta"><span><small>Released</small><b>{update.asset.updated}</b></span><span><small>Download</small><b>{update.asset.downloadSize}</b></span><span><small>Dependencies</small><b>{update.asset.dependencies}</b></span></div><div class="actions"><button class="button button-primary" type="button" onclick={()=>recordDownload(update.asset.slug,update.latestVersion)}><Icon name="download" size={17}/> Download v{update.latestVersion}</button><a class="button button-secondary" href={`/marketplace/${update.asset.slug}`}><Icon name="eye" size={17}/> View release</a><button class="later" type="button" onclick={()=>dismissUpdate(update.asset.slug,update.latestVersion)}>Hide this update</button></div></div></article>{/each}</div>{:else}<div class="empty glass"><Icon name="check" size={48}/><h2>Your library is current.</h2><p>We will surface future creator releases and compatibility changes here.</p><a class="button button-primary" href="/marketplace">Explore new assets</a></div>{/if}
<section class="current glass"><div class="panel-head"><div><span class="eyebrow">Already current</span><h2>Up-to-date products</h2></div><span>{current.length} assets</span></div><div class="current-grid">{#each current as item}<a href={`/marketplace/${item.asset.slug}`}><img src={item.asset.image} alt=""/><span><b>{item.asset.title}</b><small>v{item.asset.version} · {item.asset.compatibility}</small></span><Icon name="check" size={18}/></a>{/each}</div></section>
<style>
  .page-head{margin-bottom:20px;display:flex;align-items:end;justify-content:space-between;gap:24px}.page-head h1{margin:10px 0 7px;font-size:clamp(2.5rem,4vw,4.3rem);line-height:.96;letter-spacing:-.06em}.page-head p{margin:0;color:#aab5c8}.hero{margin-bottom:14px;padding:16px 19px;display:grid;grid-template-columns:45px 1fr auto;gap:12px;align-items:center;border-radius:14px}.hero>div{width:45px;height:45px;display:grid;place-items:center;border-radius:12px;color:#031018;background:linear-gradient(135deg,#00e5ff,#24d89a)}.hero span{display:grid}.hero b{font-size:13px}.hero small{margin-top:3px;color:#718096;font-size:8px}.hero em{padding:6px 9px;border:1px solid #27547a;border-radius:7px;color:#00e5ff;font-size:8px;font-style:normal}.updates{display:grid;gap:14px}.update{padding:13px;display:grid;grid-template-columns:300px 1fr;gap:19px;border-radius:16px}.update>img{width:100%;height:100%;min-height:265px;object-fit:cover;border-radius:11px}.copy{padding:4px 7px 4px 0}.title{display:flex;justify-content:space-between;gap:14px}.title span{display:grid}.title small{color:#8b5cf6;font-size:8px;text-transform:uppercase}.title h2{margin:5px 0 4px}.title a{color:#00e5ff;font-size:8px}.title>em{height:max-content;padding:6px 8px;border-radius:7px;color:#031018;background:#24d89a;font-size:8px;font-style:normal;font-weight:900}.copy>p{color:#aab5c8;font-size:10px;line-height:1.6}.changes{margin:14px 0;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.changes span{padding:9px;display:flex;gap:6px;align-items:center;border:1px solid #183352;border-radius:8px;color:#aab5c8;background:#050a16;font-size:8px}.changes :global(svg){color:#24d89a}.meta{display:grid;grid-template-columns:repeat(3,1fr);border-block:1px solid #122a43}.meta span{padding:11px 3px;display:grid}.meta small{color:#718096;font-size:7px}.meta b{margin-top:3px;font-size:9px}.actions{margin-top:13px;display:flex;gap:8px}.actions .button{min-height:40px;padding-inline:14px;font-size:9px}.later{border:0;color:#718096;background:transparent;cursor:pointer;font-size:8px}.later:hover{color:#f5f8ff}.current{margin-top:15px;padding:19px;border-radius:16px}.panel-head{margin-bottom:12px;display:flex;justify-content:space-between}.panel-head h2{margin:6px 0 0}.panel-head>span{color:#718096;font-size:9px}.current-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.current-grid a{padding:9px;display:grid;grid-template-columns:72px 1fr auto;gap:10px;align-items:center;border:1px solid #183352;border-radius:10px;background:#050a16}.current-grid img{width:72px;height:48px;object-fit:cover;border-radius:7px}.current-grid span{display:grid}.current-grid b{font-size:9px}.current-grid small{color:#718096;font-size:8px}.current-grid :global(svg){color:#24d89a}.empty{padding:65px;text-align:center;border-radius:18px;color:#24d89a}.empty h2{color:#f5f8ff}.empty p{color:#aab5c8}.empty .button{display:inline-flex;width:auto}
  @media(max-width:900px){.update{grid-template-columns:220px 1fr}.changes{grid-template-columns:1fr}.current-grid{grid-template-columns:1fr}}@media(max-width:650px){.page-head{align-items:start;flex-direction:column}.hero{grid-template-columns:45px 1fr}.hero em{grid-column:1/-1}.update{grid-template-columns:1fr}.update>img{min-height:190px}.actions{display:grid}.actions .button{width:100%}.title{align-items:start;flex-direction:column}.meta{grid-template-columns:1fr}}
</style>
