<script lang="ts">
  import Icon from '$lib/components/Icon.svelte';
  import { platformSettings, refreshAdminData, savePlatformSettings } from '$lib/stores/admin';
  import type { PlatformSettings } from '$lib/data/admin';
  let form:PlatformSettings={...$platformSettings};
  $: if ($platformSettings.marketplaceName !== form.marketplaceName && !form.marketplaceName) form={...$platformSettings};
  function save(){savePlatformSettings({...form});}
  async function reset(){ await refreshAdminData(); form={...$platformSettings}; }
</script>

<svelte:head><title>Marketplace settings — AssetGuru Admin</title></svelte:head>
<header class="admin-page-head"><div><span class="eyebrow">Platform configuration</span><h1>Marketplace <span class="gradient-text">settings.</span></h1><p>Commercial rules, moderation requirements, content policy and operational defaults for the AssetGuru marketplace.</p></div><div class="admin-head-actions"><button class="button button-secondary" type="button" onclick={reset}><Icon name="list" size={18}/> Reload live settings</button><button class="button button-primary" type="button" onclick={save}><Icon name="check" size={18}/> Save settings</button></div></header>

<div class="settings-layout">
  <div class="settings-main">
    <section class="admin-panel glass"><div class="admin-panel-head"><div><span class="eyebrow">Identity</span><h2>Marketplace details</h2><p>Public-facing identity and central support contact.</p></div></div><div class="admin-form-grid"><label class="admin-field"><span>Marketplace name</span><input class="admin-input" bind:value={form.marketplaceName}/></label><label class="admin-field"><span>Support email</span><input class="admin-input" type="email" bind:value={form.supportEmail}/></label><label class="admin-field"><span>Featured badge label</span><input class="admin-input" bind:value={form.featuredLabel}/><small>Used for editorially selected products.</small></label><label class="admin-field"><span>Mature content policy</span><select class="admin-select" bind:value={form.matureContent}><option>Blocked</option><option>Tagged and moderated</option></select></label></div></section>

    <section class="admin-panel glass"><div class="admin-panel-head"><div><span class="eyebrow">Commercial model</span><h2>Fees, pricing and settlement</h2><p>Defaults can later be overridden for specific vendors or categories.</p></div></div><div class="admin-form-grid"><label class="admin-field"><span>Default commission (%)</span><input class="admin-input" type="number" min="0" max="50" step="0.5" bind:value={form.defaultCommission}/></label><label class="admin-field"><span>Minimum paid price (£)</span><input class="admin-input" type="number" min="0" step="0.01" bind:value={form.minimumPrice}/></label><label class="admin-field"><span>Vendor payout delay (days)</span><input class="admin-input" type="number" min="0" max="90" bind:value={form.payoutDelay}/></label><label class="admin-field"><span>Refund request window (days)</span><input class="admin-input" type="number" min="0" max="90" bind:value={form.refundWindow}/></label><label class="admin-field"><span>Review eligibility delay (days)</span><input class="admin-input" type="number" min="0" max="30" bind:value={form.buyerReviewDelay}/><small>Helps ensure buyers have used an asset before reviewing.</small></label></div></section>

    <section class="admin-panel glass"><div class="admin-panel-head"><div><span class="eyebrow">Publication policy</span><h2>Moderation and content controls</h2></div></div><div class="toggles"><div class="admin-toggle"><span><b>Require human review</b><small>Every new product needs moderator approval.</small></span><button class:on={form.requireHumanReview} type="button" onclick={()=>form={...form,requireHumanReview:!form.requireHumanReview}} role="switch" aria-checked={form.requireHumanReview} aria-label="Toggle human review"></button></div><div class="admin-toggle"><span><b>Auto-approve low-risk updates</b><small>Only after automated package and compatibility checks pass.</small></span><button class:on={form.autoApproveUpdates} type="button" onclick={()=>form={...form,autoApproveUpdates:!form.autoApproveUpdates}} role="switch" aria-checked={form.autoApproveUpdates} aria-label="Toggle automatic updates"></button></div><div class="admin-toggle"><span><b>Allow free assets</b><small>Free listings follow the same quality standards as paid assets.</small></span><button class:on={form.allowFreeAssets} type="button" onclick={()=>form={...form,allowFreeAssets:!form.allowFreeAssets}} role="switch" aria-checked={form.allowFreeAssets} aria-label="Toggle free assets"></button></div><div class="admin-toggle"><span><b>Allow disclosed AI-assisted content</b><small>Requires lawful sourcing, disclosure and meaningful creator work.</small></span><button class:on={form.allowAiAssisted} type="button" onclick={()=>form={...form,allowAiAssisted:!form.allowAiAssisted}} role="switch" aria-checked={form.allowAiAssisted} aria-label="Toggle AI-assisted content"></button></div></div></section>
  </div>

  <aside class="settings-side">
    <section class="admin-panel glass launch"><div class="admin-panel-head"><div><span class="eyebrow">Production controls</span><h2>Current configuration</h2></div><strong>{form.maintenanceMode ? 'Paused' : 'Open'}</strong></div>{#each [{label:'Human product moderation',state:form.requireHumanReview?'Required':'Optional',done:form.requireHumanReview},{label:'Free asset publishing',state:form.allowFreeAssets?'Allowed':'Blocked',done:form.allowFreeAssets},{label:'AI-assisted content policy',state:form.allowAiAssisted?'Allowed with disclosure':'Blocked',done:form.allowAiAssisted},{label:'Support contact',state:form.supportEmail||'Not configured',done:Boolean(form.supportEmail)},{label:'Payout delay',state:`${form.payoutDelay} days`,done:true},{label:'Refund window',state:`${form.refundWindow} days`,done:true}] as item}<div class="launch-row"><i class:done={item.done}><Icon name={item.done?'check':'clock'} size={14}/></i><span><b>{item.label}</b><small>{item.state}</small></span></div>{/each}</section>

    <section class="admin-panel glass danger"><div class="admin-panel-head"><div><span class="eyebrow">Operations mode</span><h2>Maintenance control</h2></div></div><p>Maintenance mode blocks new purchases and vendor uploads while leaving buyer libraries available.</p><div class="admin-toggle"><span><b>Maintenance mode</b><small>{form.maintenanceMode?'Marketplace purchasing is paused.':'Marketplace is operating normally.'}</small></span><button class:on={form.maintenanceMode} type="button" onclick={()=>form={...form,maintenanceMode:!form.maintenanceMode}} role="switch" aria-checked={form.maintenanceMode} aria-label="Toggle maintenance mode"></button></div>{#if form.maintenanceMode}<div class="warning"><Icon name="alert" size={18}/><span><b>Purchasing will be paused</b><small>Save settings to apply maintenance mode immediately.</small></span></div>{/if}</section>

    <section class="admin-panel glass preview"><span class="eyebrow">Current fee example</span><h2>£20.00 product sale</h2><dl><div><dt>Buyer item price</dt><dd>£20.00</dd></div><div><dt>AssetGuru commission ({form.defaultCommission}%)</dt><dd>£{(20*form.defaultCommission/100).toFixed(2)}</dd></div><div><dt>Vendor allocation</dt><dd>£{(20-(20*form.defaultCommission/100)).toFixed(2)}</dd></div><div><dt>Payout availability</dt><dd>{form.payoutDelay} days</dd></div></dl><small>Tax and payment processing are accounted for separately according to the production legal model.</small></section>
  </aside>
</div>

<style>
  .settings-layout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:14px;align-items:start}.settings-main,.settings-side{display:grid;gap:14px}.toggles{display:grid;grid-template-columns:1fr 1fr;gap:9px}.launch .admin-panel-head>strong{font-size:24px;color:#24d89a}.launch-row{min-height:50px;display:grid;grid-template-columns:auto 1fr;gap:9px;align-items:center;border-top:1px solid #122a43}.launch-row i{width:30px;height:30px;display:grid;place-items:center;border-radius:8px;color:#ffb547;background:rgb(255 181 71/.08);font-style:normal}.launch-row i.done{color:#24d89a;background:rgb(36 216 154/.08)}.launch-row span{display:grid}.launch-row b{font-size:9px}.launch-row small{margin-top:3px;color:#718096;font-size:7px}.danger>p{color:#aab5c8;font-size:9px;line-height:1.6}.warning{margin-top:10px;padding:11px;display:flex;gap:9px;border:1px solid rgb(255 82 109/.3);border-radius:10px;color:#ff526d;background:rgb(255 82 109/.07)}.warning span{display:grid}.warning b{color:#f5f8ff;font-size:9px}.warning small{margin-top:3px;color:#aab5c8;font-size:7px}.preview h2{margin:12px 0}.preview dl{margin:0;display:grid}.preview dl div{min-height:42px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid #122a43}.preview dt{color:#718096;font-size:8px}.preview dd{margin:0;font-size:9px}.preview>small{display:block;margin-top:12px;color:#718096;font-size:7px;line-height:1.5}
  @media(max-width:1150px){.settings-layout{grid-template-columns:1fr}.settings-side{grid-template-columns:1fr 1fr}.settings-side .preview{grid-column:1/-1}}@media(max-width:760px){.toggles,.settings-side{grid-template-columns:1fr}.settings-side .preview{grid-column:1}}
</style>
