<script lang="ts">
  import { page } from '$app/state';
  import Icon from '$lib/components/Icon.svelte';
  import { getAsset } from '$lib/data/marketplace';
  import { buyerOrders, createSupportTicket, supportTickets } from '$lib/stores/buyer';
  let formOpen=Boolean(page.url.searchParams.get('product'));
  let subject=''; let category:'Asset support'|'Order & billing'|'Account'='Asset support';
  let productSlug=page.url.searchParams.get('product') ?? '';
  let orderId=page.url.searchParams.get('order') ?? '';
  let message=''; let filter='All';
  $: products=[...new Set($buyerOrders.flatMap((order)=>order.items.map((item)=>item.slug)))].flatMap((slug)=>{const asset=getAsset(slug);return asset?[asset]:[]});
  $: filtered=$supportTickets.filter((ticket)=>filter==='All'||ticket.status===filter);
  function submit(){if(subject.trim()&&message.trim()){createSupportTicket({subject:subject.trim(),category,productSlug:productSlug||undefined,orderId:orderId||undefined,message:message.trim()});formOpen=false;subject='';message='';}}
</script>
<svelte:head><title>Buyer support — AssetGuru</title></svelte:head>
<header class="page-head"><div><span class="eyebrow">Buyer protection</span><h1>Support <span class="gradient-text">centre.</span></h1><p>Contact the right creator with product and version context, or ask AssetGuru about orders, billing and account issues.</p></div><button class="button button-primary" type="button" onclick={()=>formOpen=true}><Icon name="plus" size={18}/> New support ticket</button></header>
<div class="support-grid">
  <section class="tickets glass"><div class="panel-head"><div><span class="eyebrow">Your cases</span><h2>Support tickets</h2></div><select bind:value={filter}><option>All</option><option>Open</option><option>Waiting on creator</option><option>Resolved</option></select></div>{#each filtered as ticket}<article class="ticket"><i class:resolved={ticket.status==='Resolved'}><Icon name={ticket.category==='Refund request'?'tag':'support'} size={19}/></i><div><div class="ticket-head"><span><b>{ticket.subject}</b><small>{ticket.id} · {ticket.category}</small></span><em class:resolved={ticket.status==='Resolved'}>{ticket.status}</em></div><p>{ticket.message}</p><div class="context">{#if ticket.productSlug&&getAsset(ticket.productSlug)}<a href={`/marketplace/${ticket.productSlug}`}>{getAsset(ticket.productSlug)?.title}</a>{/if}{#if ticket.orderId}<a href={`/account/orders/${ticket.orderId}`}>Order {ticket.orderId}</a>{/if}<span>Updated {ticket.updated}</span></div></div></article>{:else}<div class="empty"><Icon name="check" size={38}/><h3>No tickets in this view.</h3></div>{/each}</section>
  <aside><section class="routing glass"><span class="eyebrow">Smart routing</span><h2>Who handles what?</h2><div><Icon name="store" size={21}/><span><b>Creator support</b><small>Installation, asset setup, compatibility and product-specific questions.</small></span></div><div><Icon name="shield" size={21}/><span><b>AssetGuru support</b><small>Payments, refunds, licences, account access and marketplace conduct.</small></span></div></section><section class="promise glass"><Icon name="clock" size={27}/><h3>Clear response targets</h3><p>Verified creators show their typical response time. AssetGuru billing and account requests are prioritised separately.</p><a href="/support">Browse public help →</a></section></aside>
</div>
{#if formOpen}<div class="modal-backdrop" role="presentation" onclick={(event)=>{if(event.target===event.currentTarget)formOpen=false;}}><form class="modal glass" onsubmit={(event)=>{event.preventDefault();submit();}}><button class="close" type="button" onclick={()=>formOpen=false}><Icon name="close" size={18}/></button><span class="eyebrow">New case</span><h2>How can we help?</h2><div class="two"><label>Category<select bind:value={category}><option>Asset support</option><option>Order & billing</option><option>Account</option></select></label><label>Related product<select bind:value={productSlug}><option value="">No product selected</option>{#each products as asset}<option value={asset.slug}>{asset.title}</option>{/each}</select></label></div><label>Related order<select bind:value={orderId}><option value="">No order selected</option>{#each $buyerOrders as order}<option value={order.id}>{order.id} · {order.date}</option>{/each}</select></label><label>Subject<input bind:value={subject} required maxlength="100" placeholder="Describe the issue briefly"/></label><label>Message<textarea bind:value={message} required minlength="20" placeholder="Include what you expected, what happened and any steps already tried."></textarea></label><button class="button button-primary" type="submit">Create ticket</button></form></div>{/if}
<style>
  .page-head{margin-bottom:20px;display:flex;align-items:end;justify-content:space-between;gap:24px}.page-head h1{margin:10px 0 7px;font-size:clamp(2.5rem,4vw,4.3rem);line-height:.96;letter-spacing:-.06em}.page-head p{margin:0;color:#aab5c8}.support-grid{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:14px;align-items:start}.tickets,.routing,.promise{padding:19px;border-radius:16px}.panel-head{margin-bottom:8px;display:flex;justify-content:space-between}.panel-head h2{margin:6px 0 0}.panel-head select{min-height:40px;padding:0 10px;border:1px solid #183352;border-radius:8px;color:#f5f8ff;background:#050a16}.ticket{padding:16px 0;display:grid;grid-template-columns:39px 1fr;gap:11px;border-top:1px solid #122a43}.ticket>i{width:39px;height:39px;display:grid;place-items:center;border-radius:10px;color:#ffc857;background:rgb(255 200 87/.09);font-style:normal}.ticket>i.resolved{color:#24d89a;background:rgb(36 216 154/.09)}.ticket-head{display:flex;justify-content:space-between}.ticket-head span{display:grid}.ticket-head b{font-size:11px}.ticket-head small{margin-top:3px;color:#718096;font-size:8px}.ticket-head em{height:max-content;padding:5px 7px;border-radius:6px;color:#ffc857;background:rgb(255 200 87/.09);font-size:7px;font-style:normal}.ticket-head em.resolved{color:#24d89a;background:rgb(36 216 154/.09)}.ticket p{color:#aab5c8;font-size:9px;line-height:1.6}.context{display:flex;flex-wrap:wrap;gap:12px}.context a{color:#00e5ff;font-size:8px}.context span{color:#718096;font-size:8px}.routing h2{margin:8px 0 15px}.routing>div{padding:13px 0;display:flex;gap:10px;border-top:1px solid #122a43;color:#8b5cf6}.routing>div span{display:grid}.routing b{color:#f5f8ff;font-size:9px}.routing small{margin-top:3px;color:#718096;font-size:8px;line-height:1.45}.promise{margin-top:14px;color:#00e5ff}.promise h3{color:#f5f8ff}.promise p{color:#aab5c8;font-size:9px;line-height:1.55}.promise a{font-size:8px}.modal-backdrop{position:fixed;z-index:80;inset:0;padding:20px;display:grid;place-items:center;background:rgb(2 4 13/.82);backdrop-filter:blur(12px)}.modal{position:relative;width:min(650px,100%);padding:28px;border-radius:17px}.close{position:absolute;top:13px;right:13px;width:38px;height:38px;display:grid;place-items:center;border:1px solid #183352;border-radius:9px;color:#aab5c8;background:#07111f}.modal h2{font-size:26px}.modal label{margin-top:13px;display:grid;gap:7px;color:#aab5c8;font-size:9px}.modal input,.modal select,.modal textarea{padding:11px;border:1px solid #183352;border-radius:9px;outline:0;color:#f5f8ff;background:#050a16}.modal textarea{min-height:130px;resize:vertical}.modal input:focus,.modal select:focus,.modal textarea:focus{border-color:#00e5ff}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.modal>.button{width:100%;margin-top:13px}.empty{padding:60px;text-align:center;color:#24d89a}.empty h3{color:#f5f8ff}
  @media(max-width:900px){.support-grid{grid-template-columns:1fr}}@media(max-width:620px){.page-head{align-items:start;flex-direction:column}.ticket-head{align-items:start;flex-direction:column;gap:7px}.two{grid-template-columns:1fr}}
</style>
